FORMAT: 1A

# LifestyleCoach
Ultimate Matteo helper. Specifies endpoints for client users, such as JSF, mobile apps and so on.

## PersonService [/person-process]
### Create Person [POST]

+ Request (application/xml)

        <person>
            <id>0</id>
            <name>Chuck</name>
            <surname>Norris</surname>
            <birthday>1945-01-01</birthday>
            <facebookId>200500</facebookId>
            <googleId>200501</googleId>
        </person>
        
+ Response 200 (application/xml)

        <person>
            <id>101</id>
            <name>Chuck</name>
            <surname>Norris</surname>
            <birthday>1945-01-01</birthday>
            <facebookId>200500</facebookId>
            <googleId>200501</googleId>
        </person>

+ Response 406 (application/text)

        Not Acceptable

## GoalService [/goal-process]
### Create Goal [POST]

+ Request (application/xml)

        <goal>
            <id>0</id>
            <creator>
                <id>101</id>
                <name>Chuck</name>
                <surname>Norris</surname>
                <birthday>1945-01-01</birthday>
                <facebookId>200500</facebookId>
                <googleId>200501</googleId>
            </creator>
            <person>
                <id>101</id>
                <name>Chuck</name>
                <surname>Norris</surname>
                <birthday>1945-01-01</birthday>
                <facebookId>200500</facebookId>
                <googleId>200501</googleId>
            </person>
            <measureType>
                <id>3</id>
                <type>height</type>
                <unit>kilometers</unit>
            </measureType>
            <value>72.0</value>
            <message>You can do it!</message>
            <start>2014-06-10 13:53:25.945</start>
            <end>2014-06-15 13:53:25.945</end>
            <finished/>
        </goal>

+ Response 200 (application/xml)

        <goal>
            <id>101</id>
            <creator>
                <id>101</id>
                <name>Chuck</name>
                <surname>Norris</surname>
                <birthday>1945-01-01</birthday>
                <facebookId>200500</facebookId>
                <googleId>200501</googleId>
            </creator>
            <person>
                <id>101</id>
                <name>Chuck</name>
                <surname>Norris</surname>
                <birthday>1945-01-01</birthday>
                <facebookId>200500</facebookId>
                <googleId>200501</googleId>
            </person>
            <measureType>
                <id>3</id>
                <type>height</type>
                <unit>kilometers</unit>
            </measureType>
            <value>72.0</value>
            <message>You can do it!</message>
            <start>2014-06-10 13:53:25.945</start>
            <end>2014-06-15 13:53:25.945</end>
            <finished/>
        </goal>

+ Response 406 (application/text)

        Not Acceptable

## MeasureService [/measure-process]
### Create Measure [POST]

+ Request (application/xml)

        <measure>
            <id>0</id>
            <person>
                <id>101</id>
                <name>Chuck</name>
                <surname>Norris</surname>
                <birthday>1945-01-01</birthday>
                <facebookId>200500</facebookId>
                <googleId>200501</googleId>
            </person>
            <measureType>
                <id>3</id>
                <type>height</type>
                <unit>kilometers</unit>
            </measureType>
            <value>72.1</value>
            <created>2014-06-12 13:53:26.70</created>
        </measure>

+ Response 200 (application/xml)

        <measure>
            <id>101</id>
            <person>
                <id>101</id>
                <name>Chuck</name>
                <surname>Norris</surname>
                <birthday>1945-01-01</birthday>
                <facebookId>200500</facebookId>
                <googleId>200501</googleId>
            </person>
            <measureType>
                <id>3</id>
                <type>height</type>
                <unit>kilometers</unit>
            </measureType>
            <value>72.1</value>
            <created>2014-06-12 13:53:26.70</created>
        </measure>

+ Response 406 (application/text)

        Not Acceptable

## MotivationService [/motivation-process/{personId}]

+ Parameters
    + personId (required, number, `1`) ... Id of the person we want to motivate.

### Get Motivated [GET]
+ Response 200 (application/xml)

        <motivation>
            <type>text</type>
            <value>Chuck Norris uses ribbed condoms inside out, so he gets the pleasure.</value>
        </motivation>

+ Response 406 (application/text)

        Not Acceptable

## AwarenessService [/awareness-process/{personId}]

+ Parameters
    + personId (required, number, `1`) ... Id of the person we want to aware.

### Get Motivated [GET]
+ Response 200 (application/xml)

        <awareness>
            <type>severe</type>
            <value>Chuck, you gonna die.</value>
        </awareness>

+ Response 406 (application/text)

        Not Acceptable

## ProgressService [/progress-process/{personId}]

+ Parameters
    + personId (required, number, `1`) ... Id of the person we want to progress.

### Get Motivated [GET]
+ Response 200 (application/xml)

        <progress>
            <type>You</type>
            <value>Suck</value>
        </progress>

+ Response 406 (application/text)

        Not Acceptable

## WorkoutService [/workout-process/{personId}]

+ Parameters
    + personId (required, number, `1`) ... Id of the person we want to workout.

### Get Motivated [GET]
+ Response 200 (application/xml)

        <workout>
            <name>Incline Plank with alternate floor touch</name>
            <description>Perform the plank with legs elevated, feet on a gymball. Once stabilised, slowly move one foot sideways off the ball, then make it touch the floor, then come back to starting position. Alternate with the other foot. This is a core exercise.</description>
        </workout>

+ Response 406 (application/text)

        Not Acceptable
